### ISSUE TITLE
Unable to remove DOI with fixture data

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_describe#1325]
I was told by @kelynch to create ticket if an issue arise. I went into the metadata for one of the fixtures that has an incorrect DOI specified to adjust it before approving it. I removed it and upon saving it, it still shows the original entered DOI. See screenshots below.

It seems as that DOI is not permanently hardcoded after you create the dataset if you manually enter it.

Removed and saved work:
<img width="1348" alt="Screen Shot 2023-07-13 at 11 04 10 AM" src="https://github.com/pulibrary/pdc_describe/assets/20305734/2aca5b98-ad86-4f26-9886-1b28f942329c">

Still see it.
<img width="875" alt="Screen Shot 2023-07-13 at 11 04 21 AM" src="https://github.com/pulibrary/pdc_describe/assets/20305734/bb3c5ef1-5685-470e-b18c-28c827fd30d3">

**Comment by carolyncole** [comment]
Chatted with @astrochun over slack.  We (The developers) can modify the JSON on the fixture before we import the record to force the system to mint a DOI.  We may want to add a feature to allow a used to request a newly minted DOI instead of the current one.  We will leave this bug open until @astrochun can verify if updating the JSON before importing does the fix he was expecting later this week.

**Comment by astrochun** [comment]
@carolyncole, I'm still a bit confused. I went into PDC Describe Prod to look at this record and the Zenodo DOI is still being used. I had thought that you changed it and minted a new Princeton DOI

https://pdc-describe-prod.princeton.edu/describe/works/44

**Comment by carolyncole** [comment]
I created a separate ticket for the updates related to the DOI being wrong #1351

**Comment by astrochun** [comment]
Thanks. I will close out this ticket once I publish these three.

**Comment by carolyncole** [comment]
@astrochun can we close this ticket?

**Comment by astrochun** [comment]
Yes, sorry.
