### ISSUE TITLE
Moderators cannot change groups for submissions

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#1355]
Moderators should be able to add or switch objects to pipelines of which they are moderators (PRDS or PPPL at this time).  @Twade968 reported and demonstrated at stand-up today that he cannot switch an object from the PRDS pipeline to the PPPL group in production, despite being a moderator for both groups.

**Comment by hectorcorrea** [comment]
@Twade968 and I found a work-around. Tyler was a moderator for PPPL but not a submitter, because of this he was able to add himself as a submitter and now the dropdown list to select the right Group for works is enabled for him.

We should fix the logic in the dropdown list to account for this, though.

**Comment by kelynch** [comment]
Closed with #1378
