### ISSUE TITLE
Files not migrating 

### ISSUE THREAD

**Issue by neggink** [pulibrary/pdc_describe#1919]
### Expected behavior
All data files migrated for the dataset: https://pdc-describe-prod.princeton.edu/describe/works/469

### Actual behavior
Only 1 (the readme) of the 3 files migrated. 

The files are in both DataSpace and Globus. The history log in PDC shows that the files started to migrate but then are deleted by "Unknown user outside the system".
<img width="539" alt="Screenshot 2024-09-09 at 4 17 25 PM" src="https://github.com/user-attachments/assets/5f799ef5-9eec-471c-b706-8df2ecdfdf4c">

### Impact of this bug
Cannot finish migrating this dataset

### Acceptance Criteria

- [ ] Investigate the logs to see if there is something simple going on
- [ ] Copy the files from Globus to PDC describe

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1919?planning-poker) with Zenhub @bess @hectorcorrea @JaymeeH @leefaisonr

**Comment by carolyncole** [comment]
The files are in a strange location in AWS.  s3://pdc-describe-prod-precuration/10-3477010.34770/9ndy-8c50/469/9ndy-8c5010.34770/9ndy-8c50/469/ instead of s3://pdc-describe-prod-precuration/10.34770/9ndy-8c50/469/ (Note the odd top directory and looping path) I'm going to move them, but I am wondering if there is something going on with the curation workstation or something...  I can not image what...  I'm thinking I move them, we wait a day and see if they stay put...

**Comment by carolyncole** [comment]
Turns out the migration put them into a funky spot and then could not find them later...
![Screenshot 2024-09-27 at 8 46 40 AM](https://github.com/user-attachments/assets/e4e21fd9-c24b-4371-95fe-d1448603fd7d)
