### ISSUE TITLE
Describe test records to validate our ability to migrate DataSpace research data

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#229]
One of our goals for data migration is to have 5 - 10 sample objects for which we have:

* Validated description in our submission form
* Solid, well tested indexing and display in PDC Discovery

In order to deliver this, we will:

* Describe representative test records using rspec system specs (see, e.g., spec/system/bitklavier_form_submission_spec.rb)
* Validate the DataCite records that are produced by that system spec with our data curators
* Move the metadata produced by that system spec into our staging system (Documentation on how to do this is [here](https://github.com/pulibrary/pdc_describe/blob/main/docs/test_data_in_production.md))
    
This will give us a known and consistent target to work with as we zero in on how to index these works for PDC Discovery.

## Resources:
* [Other fixtures](https://docs.google.com/document/d/18ZkBldqWxIIR1UA6qMY87RnGFTKU9HG3EJzodzzFf2A/edit#heading=h.cj3zec9ihjhc)

**Comment by hhkitsune** [comment]
## Note

Please reach out to me before implementing a change in metadata for the legacy records. In addition to differences between the schema, some liberties were taken with applying Dublin Core and there are some changes in how we want to optimally describe assets moving forward.  

## Description

The following table shows Dublin Core from the record in this ticket and the complementary Datacite property. The Datacite property will link to the part of the schema 4.4 help document that discusses the specific property. 

*Some Dublin Core will not map neatly to Datacite. I have noted properties that I'm seeking further input on. I will update the table and notify RDSS when I have gathered more complete information.*

|   Dublin Core   |   Datacite   | Notes |
| :------------- | :------------- | :------------- |
| Title | [Title](https://support.datacite.org/docs/datacite-metadata-schema-v44-mandatory-properties#3-title) | |
| Contributors | [Creator](https://support.datacite.org/docs/datacite-metadata-schema-v44-mandatory-properties#2-creator) | In the context of this example, the "contributors" are "creators" of the work. Note that an additional field for "[contributor](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#7-contributor)" in Datacite regards non-authoring contributors of the deposit. |
| Issue Date | [PublicationYear](https://support.datacite.org/docs/datacite-metadata-schema-v44-mandatory-properties#5-publicationyear) | This is the year the object was published to the repository. Hector has made this automatic for the Describe Form. |
| Related Publication | placeholder | HH looking into nuance of this. |
| Abstract | [Description](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#17-description), with sub-property [descriptionType](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#17a-descriptiontype); suggest "abstract" from controlled list for sub-property |  This will be something to discuss further, because "abstract" is too suggestive of the associated paper's abstract for a depositor to always understand what we are asking for, which is a unique description of the deposited data, code or other object. For the new form and metadata, we want to encourage "Description" to capture this information, but may want to optionally allow a choice of description types, if someone wants to get more specific. Please reach out if you want to talk about this. |
| Description | [Description](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#17-description), with sub-property [descriptionType](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#17a-descriptiontype); suggest "other" from controlled list for sub-property | The blurb entered to this field is fine for a supplementary description, though it wouldn't stand as a good description on it's own. If this record didn't also contain the "abstract" then a summary description should be taken from the README (if the submitter is unavailable), because we need a good description that will include searchable terms to be indexed by search engines. Additionally, an end-user shouldn't have to access the README to understand if this deposit is what they are looking for. |
| URI | <ul><li>For a DOI minted with Datacite: [Identifier](https://support.datacite.org/docs/datacite-metadata-schema-v44-mandatory-properties#1-identifier) </li><li>For an ARK: [AlternateIdentifier with mandatory sub-property](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#11-alternateidentifier) | Some legacy records may only have an ARK, but new records (and some legacy) will have the DOI minted via Datacite that should be used with Identifier. |
| Appears in Collections | placeholder | To be discussed further with Wind who has concerns about continuing to organize our records in this manner. It may still be useful categorization, but we might not make this as prominent as before. |

**Comment by hhkitsune** [comment]
@Bess (@kelynch fyi ) I think we are going to need to talk further about how the metadata in Dublin Core will be translated to Datacite. There are cases where this may not move neatly. 

For example, Neggin shared this record with me: [Supplement to PhD Dissertation: "Subsurface Computational Modeling and Policy Analysis of Large-Scale Carbon Capture, Utilization, and Storage (2022)"](https://dataspace.princeton.edu/handle/88435/dsp01n870zt98h)

"Referenced By" in Neggin's example and "Related Publication" in Bess's example (if an ID is available for the publication) may both fall under the "RelatedIdentifer" property in Datacite, but may use different selections from the controlled lists in the subproperties. (See: [RelatedIdentifier in Datacite 4.4](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#12a-relatedidentifiertype)) As is, Bess's example might use "Related Item" for a better fit to Datacite. (See: [Related Item property in Datacite 4.4](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#20-relateditem)) 

**It will be important to check that both of these fields in Dublin Core/DataSpace have been used consistently, before assuming which of the aforementioned Datacite properties should be applied.**  

Additionally, we should discuss whether some Dublin Core properties have information that we don't want transferred to Datacite. These might contain information that isn't needed or desired in the new infrastructure. For example, I think Wind will have some thoughts on "Collection" for the main collection. However, these may be important to keep in place for PPPL. In Bess's example, "Description" is capturing an auto-generated message about the README that might not be useful -- but that's something we need to discuss.
