### ISSUE TITLE
Produce migration spec for bitKlavier Piano Bar Mic Image

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#471]
Following the example of [our bitKlavier rspec test ](https://github.com/pulibrary/pdc_describe/blob/main/spec/system/bitklavier_form_submission_spec.rb), produce system specs to migrate this object:

[bitKlavier Grand Sample Library—Piano Bar Mic Image ](https://dataspace.princeton.edu/handle/88435/dsp015999n653h)

### Acceptance Criteria
- [x] The Rspec test re-describes this work according to RDOS guidelines for DataCite description
- [x]  Ask for sign-off on DataCite record from Matt or Neggin.

**Comment by neggink** [comment]
There is a typo in the description: "pedalU2.wav" **=&gt** should be "pedalU2.wav **=>**

We should remove the last two sentences from the description "This dataset is too large to download directly from this item page. You can access and download the data via Globus (See https://www.youtube.com/watch?v=uf2c7Y1fiFs for instructions on how to use Globus)."

Otherwise, it looks good. Thanks!
