### ISSUE TITLE
Missing field for related identifier

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#486]
During our work building this migration spec: This migration test work: https://github.com/pulibrary/pdc_describe/blob/main/spec/system/cytoskeletal_form_submission_spec.rb

we uncovered the fact that we're missing a field for "Related Identifier", specifically this one: https://www.biorxiv.org/content/10.1101/545517v1

### Acceptance Criteria
- [x] Talk to RDOS and decide what relationship we want to say the dataset has to the paper
- [x] Write a ticket describing:
  - [x] What that field should look like in the UI
  - [x] How (or whether) that data should appear in the DataCite record
  - [x] How that data should appear on the "show" page for this work

**Comment by matthewjchandler** [comment]
Mapping relation definitions from DSpace to DataCite can be tricky. In our ongoing curation, we interpret "dc.relation.isreferencedby" from DSpace (see https://wiki.lyrasis.org/display/DSDOC5x/Metadata+and+Bitstream+Format+Registries) as "IsCitedBy" in DataCite. There can be confusion because DataCite also has an "IsReferencedBy" relation, but "IsCitedBy" is the current recommendation, so that is what we use for relations between datasets and their corresponding papers (see https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#12b-relationtype).

**Comment by hhkitsune** [comment]
@bess Regarding how data should appear in Discovery for the related identifier and its controlled variables, please see this example in Zenodo: [Sample; related identifier and subfield](https://zenodo.org/record/7185360#.Y0gvYlLML0s)

### The image shows a sample record in Zenodo's UI that is using the [(12) RelatedIdentifer](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#12-relatedidentifier) property with a variable from the controlled list in [(12.b) relationType](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#12b-relationtype). 

(Note that [(12.a) relatedIdentifierType](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#12a-relatedidentifiertype) would be inputted to the form because it's a mandatory property when using 12 RelatedIdentifier, but this does not explicitly show on the discovery page. Please see the wireframes for the Describe form for how this set of properties should appear in the Describe form.)

![Screen Shot 2022-10-13 at 11 33 31 AM](https://user-images.githubusercontent.com/50670293/195644169-2e6748d7-b49f-424e-be60-c42c652e52eb.jpeg)

**Comment by bess** [comment]
Ticket here: https://github.com/pulibrary/pdc_describe/issues/494

**Comment by bess** [comment]
I've broken out the display in discovery into its own ticket to make it actionable and trackable: https://github.com/pulibrary/pdc_discovery/issues/349
