### ISSUE TITLE
Utilize s3 copy_to instead of downloading and uploading

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#538]
Currently the code downloads and then uploads the S3 object to transfer from pre-curation to post-curation.

This will be too costly for large files. Instead we should utilize the S3 copy_to, which does it all in Amazon in one step.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/example_s3_CopyObject_section.html

Here is the line that does a download and an upload: https://github.com/pulibrary/pdc_describe/blob/13ea421954f969fa735e61c88c79bba1638df337/app/models/work.rb#L719

Acceptance criteria:

- [ ] The copy to api is utilized in the work (see example link above)
- [ ] There is an automated to make sure we are not doing a get and put on amazon S3

**Comment by hectorcorrea** [comment]
[This page on the S3 User Guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/copy-object.html) shows more or less what happens when using `copy_object`. It seems that the API will:

* issue a PUT with the target filename 
* passing the target bucket in `host` header
* and the source information (bucket and filename) in the `x-amz-copy-source` header

Below is an example (from the user guide) copying `atlantic/jetsam` to `/pacific/flotsam`

```
PUT /jetsam HTTP/1.1
Host: atlantic.s3.amazonaws.com
x-amz-copy-source: /pacific/flotsam
...
```
