### ISSUE TITLE
Only curators should be able to modify approved items

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#833]
Curators should be able to modify objects after they have been approved.

Test to ensure that curators can modify objects that they themselves submitted after they have been approved.

Additional titles for a Work are not being saved *when the work has already been approved*. Although I can edit the work and add a new title via the `+` button, the title is **not** saved on the work.
 
![add_title_edit](https://user-images.githubusercontent.com/568286/211367029-1534f7f1-d63d-4128-89a5-acef3363009e.png)

No error is reported to the user during Save, but the system goes back to the home page rather than displaying the Show page for the work after save.

The system works as expected when the title is added to a work that has not yet been approved.

Related to https://github.com/pulibrary/pdc_discovery/issues/340

**Comment by jrgriffiniii** [comment]
I am having trouble reproducing this, as I am able to successfully test for this (please see https://github.com/pulibrary/pdc_describe/compare/issues-833-mult-titles?expand=1). Perhaps this is related to certain permissions not being properly set for the users?

**Comment by carolyncole** [comment]
I feel like this was by design.  Maybe the edit button should be removed.  Aka I think we had a requirement that stated: Once the work is approved the depositor should no longer be able to edit the work.  I'll look around and see if I can find some supporting documentation @hectorcorrea and @jrgriffiniii

**Comment by carolyncole** [comment]
The requirement that a user can not edit an item they deposited was ticketed here: https://github.com/pulibrary/pdc_describe/issues/255

**Comment by carolyncole** [comment]
@kelynch gathered more information: https://pulibrary.slack.com/archives/C02PHG9MGU8/p1674155262416529

**Comment by carolyncole** [comment]
So I believe the actual bug is, as the depositor of a work and a collection curator, I should be able to update a work after it has been approved.
So this line https://github.com/pulibrary/pdc_describe/blob/main/app/controllers/works_controller.rb#L117 should allow edits if the current user is a curator of the collection, NOT as I coded it to exclude the depositor.
